version: "3"

tasks:
  format:
    cmds:
      - ruff check . --select I --fix
      - ruff format .

  clean:
    cmds:
      - rm -rf dist
      - find . -type f -name "*.DS_Store" -ls -delete
      - find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
      - find . | grep -E ".pytest_cache" | xargs rm -rf
      - find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
      - rm -f .coverage

  clean-logs: rm -rf logs/**

  sync:
    cmds:
      - git pull
      - git pull origin main

  train: python src/train.py {{.CLI_ARGS}}

  eval: python src/eval.py {{.CLI_ARGS}}

  explain: python src/explain.py {{.CLI_ARGS}}

  cross-validate: python src/cross_validate.py -m {{.CLI_ARGS}}

  convert-nc:
    vars:
      NC_FILE_LIST:
        sh: echo {{.NC_FILES}} | sed -e "s/ /\n/g" | sed -e "s/\(.*\)/'\1',/g" | tr -d "\n"
    cmds:
      - python
          scripts/nc_to_np.py
          convert_multiple
          --output-dir=data
          --variable-name={{.VAR_NAME}}
          --input-files="[{{.NC_FILE_LIST}}]"

  venv:
    vars:
      VENV_PATH: venv
    preconditions:
      - sh: "[ ! -d {{.VENV_PATH}} ]"
    cmds:
      - python -m venv {{.VENV_PATH}}
