defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

run:
  dir: ${paths.log_dir}/${task_name}/runs/${job_name}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${job_name}
  subdir: ${hydra.job.num}_${job_name}

job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${task_name}.log

job:
  config:
    override_dirname:
      kv_sep: '='
      item_sep: ','
      exclude_keys: []
