_target_: src.models.module.Model

loss_fun:
  _target_: torch.nn.MSELoss

net:
  _target_: src.models.components.ensemble.TorchEnsemble
  model_cls: src.models.components.dense.MLPModel
  num_models: 50
  input_dim: 3
  hidden_dim: 128
  n_hidden: 2
