_target_: src.models.time_series_module.Model

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.001

scheduler: null

loss_fun:
  _target_: torch.nn.MSELoss

net:
  _target_: src.models.components.recurrent.RNNModel
  input_dim: 10
  hidden_dim: 128
  output_dim: 1
  num_layers: 2
  recurrent_type: gru
