_target_: src.models.time_series_module.Model

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.001

scheduler: null

loss_fun:
  _target_: torch.nn.MSELoss

net:
  _target_: src.models.components.dense.MLPModel
  input_dim: 3
  hidden_dim: 128
  n_hidden: 2
