_target_: src.models.module.Model

loss_fun:
  _target_: torch.nn.MSELoss

net:
  _target_: src.models.components.recurrent.RNNModel
  input_dim: 10
  hidden_dim: 128
  output_dim: 1
  num_layers: 2
  recurrent_type: rnn
