box_model:
  S0: 35.0
  T0: 24.0
  S1: 12
  S2: 20
  T1: 1
  T2: 10
  area: 2500000000000000 # (50000.0e3) ** 2
  k: 10000000000 # 10e9
  depth: 4000
  alpha: 0.2
  beta: 0.8

data:
  seq_len: &seq_len 10
  test_size: 0.3

model:
  model_type: bayes_mlp
  explain_after_train: True
  seq_len: *seq_len
  num_models: 20
  num_epochs: 50
  batch_size: 32
  lr: 0.0001
  l2_alpha: 3e-3
  hidden_size: 64
  num_layers: 2
