# @package _global_

defaults:
  - _self_
  - data: physics_informed
  - box_model: basic
  - density: linear
  - s_forcing: linear_symmetric
  - t_forcing: linear_symmetric
  - model: mlp
  - callbacks: default
  - logger: csv
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - explainability:
    - shap
    - lrp
  - plotting:
    - data
    - groundtruth_prediction
    - bias
    - loss_landscape
  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

task_name: "train"
tags: ["dev"]
train: True
test: False
ckpt_name: null
seed: null
