model_type: mlp
num_models: 50
num_epochs: 10
batch_size: 32
loss_fun: nn.MSELoss
lr: 0.0001
l2_alpha: 3e-3
hidden_size: 64
num_layers: 2
device: mps
plot_results: True
show_change_points: False
compute_bias: True
log_grad_norm: True
explain_ylabel: Shapley Values
loggers:
  lightning.pytorch.loggers.CSVLogger:
    save_dir: "."
    version: mlp